DROP DATABASE IF EXISTS PRACTICA26;
CREATE DATABASE IF NOT EXISTS PRACTICA26
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

SHOW DATABASES;
USE PRACTICA26;

CREATE TABLE PINACOTECA(
	nombre VARCHAR(150) PRIMARY KEY,
    direccion VARCHAR(200) NOT NULL,
    metroscuadrados INTEGER (50),
    ciudad VARCHAR(100) NOT NULL
);

CREATE TABLE PINTOR(
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    nif VARCHAR(15) NOT NULL UNIQUE,
    fechaNacimiento DATE NOT NULL,
    fehcaFin DATE NOT NULL,
    maestro INTEGER NOT NULL,
CONSTRAINT FK1_REFLEXIVA FOREIGN KEY(maestro) REFERENCES PINTOR(codigo) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE CUADRO(
	codigo INTEGER PRIMARY KEY,
	nombre VARCHAR(150) NOT NULL,
    fecha DATE NOT NULL,
    tecnica  VARCHAR(150) NOT NULL,
    pinacoteca VARCHAR(200) NOT NULL,
    pintor INTEGER NOT NULL,
CONSTRAINT FK2_CUADRO_PINACOTECA FOREIGN KEY(pinacoteca) REFERENCES PINACOTECA(nombre) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK3_CUADRO_PINTOR FOREIGN KEY(pintor) REFERENCES PINTOR(codigo) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE ESCUELA(
	nombre VARCHAR(150) PRIMARY KEY,
    pais VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL
);

CREATE TABLE ESCUELAPINTOR(
	pintor INTEGER,
    escuela VARCHAR(150),
CONSTRAINT FK4_MULTIPLE PRIMARY KEY (pintor,escuela),
CONSTRAINT FK5_PINTOR FOREIGN KEY (pintor) REFERENCES PINTOR(codigo) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK6_ESCUELA FOREIGN KEY (escuela) REFERENCES ESCUELA(nombre) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE MECENAS(
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    pais VARCHAR(200) NOT NULL,
    fechaInicio DATE NOT NULL,
    fehaFin DATE
);

CREATE TABLE PINTORMECENA(
	codigoPintor INTEGER,
    codigoMecena INTEGER,
    fehaI DATE NOT NULL,
    fechaF DATE NOT NULL,
CONSTRAINT FK7_MULTIPLE PRIMARY KEY (codigoPintor,codigoMecena),
CONSTRAINT FK8_PINTORMECENA_PINTOR FOREIGN KEY (codigoPintor) REFERENCES PINTOR(codigo),
CONSTRAINT FK9_PINTORMECENA_MECENA FOREIGN KEY (codigoMecena) REFERENCES MECENAS(codigo)
);

DESCRIBE PINACOTECA;
DESCRIBE PINTOR;
DESCRIBE CUADRO;
DESCRIBE ESCUELA;
DESCRIBE ESCUELAPINTOR;
DESCRIBE MECENAS;
DESCRIBE PINTORMECENA;