DROP DATABASE IF EXISTS PRACTICA24;
CREATE DATABASE IF NOT EXISTS PRACTICA24
DEFAULT CHARACTER SET UTF8 COLLATE utf8_general_ci;

SHOW DATABASES;
USE PRACTICA24;

CREATE TABLE OPOSITORES(
	id INTEGER PRIMARY KEY,
	nombre VARCHAR (150) NOT NULL,
	nacimiento DATE NOT NULL,
	telefono VARCHAR(9) NOT NULL UNIQUE
);

CREATE TABLE EXAMENES(
	id INTEGER PRIMARY KEY,
	tipo INTEGER NOT NULL, /*1=TIPO TEST 0=ESCRITO */
	porcentaje INTEGER NOT NULL,
	duracion TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS CALIFICACIONES(
	id INTEGER PRIMARY KEY,
	fecha DATE NOT NULL,
	calificaciones DECIMAL NOT NULL,
	opositor INTEGER NOT NULL,
	examen INTEGER NOT NULL,
CONSTRAINT FK1_CALIFICACIONES_OPOSITOR FOREIGN KEY(opositor) REFERENCES OPOSITORES(id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK2_CALIFICACIONES_EXAMEN FOREIGN KEY(examen) REFERENCES EXAMENES(id) ON UPDATE CASCADE ON DELETE CASCADE

);

DESCRIBE OPOSITORES;
DESCRIBE EXAMENES;
DESCRIBE CALIFICACIONES;