DROP DATABASE IF EXISTS PRACTICA25;
CREATE DATABASE IF NOT EXISTS PRACTICA25
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE PRACTICA25;

CREATE TABLE EMPLEADO(
	id INTEGER PRIMARY KEY,
    nombre VARCHAR (150) NOT NULL,
    DNI VARCHAR(15) NOT NULL,
    jefe INTEGER, /* Atributo reflexivo */
CONSTRAINT FK1_REFLEXIVA FOREIGN KEY(jefe) REFERENCES EMPLEADO(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE PROYECTO(
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(250) NOT NULL
);

CREATE TABLE ASIGNACION(
	id INTEGER,
    codigo INTEGER,
	/* Al ser claves primarias ambas, se crea con un constraint*/
CONSTRAINT PK_MULTIPLE PRIMARY KEY (id,codigo),
CONSTRAINT FK2_ASIGNACION_PROYECTO FOREIGN KEY(id) REFERENCES EMPLEADO(id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK3_ASIGNACION_PROYECTO FOREIGN KEY(codigo) REFERENCES PROYECTO(codigo) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE VEHICULO(
	matricula VARCHAR(7) PRIMARY KEY,
    marca VARCHAR(250) NOT NULL,
    modelo VARCHAR(250) NOT NULL,
    PERSONA INTEGER,
CONSTRAINT FK4_VEHICULO_PERSONA FOREIGN KEY(persona) REFERENCES EMPLEADO(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DESCRIBE EMPLEADO;
DESCRIBE PROYECTO;
DESCRIBE ASIGNACION;
DESCRIBE VEHICULO;