DROP DATABASE IF EXISTS PRACTICA27;
CREATE DATABASE IF NOT EXISTS PRACTICA27
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

SHOW DATABASES;
USE PRACTICA27;

CREATE TABLE JUEZ(
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    fecha DATE
);

CREATE TABLE PERIODICO(
	nombre VARCHAR(100) PRIMARY KEY,
    direccion VARCHAR(200) NOT NULL,
    tirada INTEGER NOT NULL
);

CREATE TABLE CASO(
	codigo INTEGER PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    dinero INTEGER NOT NULL,
    juez INTEGER NOT NULL,
    dictamen VARCHAR(100) NOT NULL,
    periodico VARCHAR(100) NOT NULL,
    fecha DATE,
CONSTRAINT FK1_CASO_JUEZ FOREIGN KEY(juez) REFERENCES JUEZ(codigo) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK32_CASO_PERIODICO FOREIGN KEY(periodico) REFERENCES PERIODICO(nombre) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE CIUDADANO(
	dni VARCHAR(15) PRIMARY KEY,
    nombre VARCHAR(250) NOT NULL,
    direccion VARCHAR(250),
    patrimonio INTEGER(100)
);

CREATE TABLE IMPLICADO(
	caso INTEGER NOT NULL,
    ciudadano VARCHAR(15) NOT NULL,
    cargo VARCHAR(200),
CONSTRAINT FK3_MULTIPLE PRIMARY KEY(caso,cargo),
CONSTRAINT FK4_IMPLICADO_CASO FOREIGN KEY (caso) REFERENCES CASO(codigo) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK5_IMPLICADOS_CIUDADANO FOREIGN KEY(ciudadano) REFERENCES CIUDADANO(dni) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE PARTIDO (
	nombre VARCHAR(150) PRIMARY KEY,
    direccion VARCHAR(200) NOT NULL,
    telefono INTEGER (12)
);

CREATE TABLE PERTENECE(
	dniCiudadano VARCHAR(15) PRIMARY KEY,
    partidoPolitico VARCHAR(150) NOT NULL,
    puesto VARCHAR (50),
CONSTRAINT FK6_PERTENECE_CIUDADANO FOREIGN KEY (dniCiudadano) REFERENCES CIUDADANO(dni) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK7_PERTENECE_PARTIDO FOREIGN KEY(partidoPolitico) REFERENCES PARTIDO(nombre) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE AFIN(
	periodico VARCHAR(100) PRIMARY KEY,
    partidoPolitico VARCHAR(150),
CONSTRAINT FK8_AFIN_PERIODICO FOREIGN KEY(periodico) REFERENCES PERIODICO(nombre) ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK9_AFIN_PARTIDO FOREIGN KEY (partidoPolitico) REFERENCES PARTIDO(nombre) ON UPDATE CASCADE ON DELETE NO ACTION
);

DESCRIBE JUEZ;
DESCRIBE PERIODICO;
DESCRIBE CASO;
DESCRIBE CIUDADANO;
DESCRIBE IMPLICADO;
DESCRIBE PARTIDO;
DESCRIBE PERTENECE;
DESCRIBE AFIN;