DROP DATABASE IF EXISTS DISCOMUSICA;
CREATE DATABASE IF NOT EXISTS DISCOMUSICA
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

SHOW DATABASES;
USE DISCOMUSICA;

CREATE TABLE ESTILOS(
	id INTEGER PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL
    
);

CREATE TABLE ARTISTAS(
	id INTEGER PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    fundacion YEAR NOT NULL,
    miembros INTEGER NOT NULL DEFAULT 0,
    pais VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS DISCOS(
	id INTEGER PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    publicacion YEAR NOT NULL,
    estuche INTEGER NOT NULL,
    original INTEGER NOT NULL,
    artista INTEGER NOT NULL,
    estilo INTEGER NOT NULL,
    CONSTRAINT FK1_DISCOS_ARTISTAS FOREIGN KEY (artista) REFERENCES ARTISTAS(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT FK2_DISCOS_ESTILOS FOREIGN KEY (estilo) REFERENCES ESTILOS(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DESCRIBE ESTILOS;
DESCRIBE ARTISTAS;
DESCRIBE DISCOS;